import { Session } from '../types';

export const mockSessions: Session[] = [
  {
    id: '1',
    tutorId: 'tutor1',
    tutorName: 'Sarah Chen',
    skillTitle: 'Guitar Basics',
    description: 'Learn fundamental guitar chords and strumming patterns in this beginner-friendly session.',
    duration: 30,
    creditCost: 2,
    tags: ['Music', 'Guitar', 'Beginner'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    tutorId: 'tutor2',
    tutorName: 'Mike Johnson',
    skillTitle: 'Photography Crash Course',
    description: 'Master composition, lighting, and basic editing techniques for stunning photos.',
    duration: 45,
    creditCost: 3,
    tags: ['Photography', 'Art', 'Intermediate'],
    createdAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    tutorId: 'tutor3',
    tutorName: 'Emma Wilson',
    skillTitle: 'JavaScript Fundamentals',
    description: 'Understanding variables, functions, and DOM manipulation for web development.',
    duration: 60,
    creditCost: 4,
    tags: ['Programming', 'JavaScript', 'Web Development'],
    createdAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    tutorId: 'tutor4',
    tutorName: 'David Kim',
    skillTitle: 'Spanish Conversation',
    description: 'Practice everyday Spanish conversation skills and improve your pronunciation.',
    duration: 30,
    creditCost: 2,
    tags: ['Language', 'Spanish', 'Conversation'],
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    tutorId: 'tutor5',
    tutorName: 'Lisa Garcia',
    skillTitle: 'Digital Marketing Basics',
    description: 'Learn about social media marketing, SEO basics, and content creation strategies.',
    duration: 50,
    creditCost: 3,
    tags: ['Marketing', 'Digital', 'Business'],
    createdAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    tutorId: 'tutor6',
    tutorName: 'Alex Rodriguez',
    skillTitle: 'Yoga for Beginners',
    description: 'Introduction to basic yoga poses, breathing techniques, and mindfulness.',
    duration: 40,
    creditCost: 2,
    tags: ['Fitness', 'Yoga', 'Wellness'],
    createdAt: new Date('2024-01-10'),
  },
];

export const availableTags = [
  'Programming', 'JavaScript', 'Web Development', 'Python', 'React',
  'Music', 'Guitar', 'Piano', 'Art', 'Photography',
  'Language', 'Spanish', 'French', 'English',
  'Marketing', 'Digital', 'Business', 'Finance',
  'Fitness', 'Yoga', 'Wellness', 'Cooking',
  'Design', 'UI/UX', 'Graphic Design',
  'Beginner', 'Intermediate', 'Advanced'
];